name: Example Integration on Push
on:
  push:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Donate
        id: donate
        uses: goodcall-one/github_action@main
        with:
        # Enter your API variables below
            apikey: ${{ secrets.donation_apikey }}
            organization_id: "7C47010611E5FB5D"
            user: ${{ github.actor }}
            wallet_id: "884b5313-259e-4711-9552-60c5f76b427e"
            test: "false"

      - name: Response of goodcall.one API
        run: |
            echo "${{ steps.donate.outputs.response }}"
